In [1]:
import numpy as np

In [2]:
revenue = np.array([[30000,13500,26000],[24000,56000,35000],[23000,49000,36000]])
Expenses = np.array([[18000,12000,14000],[15000,35000,24000],[13000,38000,27000]])

In [4]:
profit = revenue - Expenses
profit

array([[12000,  1500, 12000],
       [ 9000, 21000, 11000],
       [10000, 11000,  9000]])

In [5]:
Price = np.array([24000,15000,10000])
Units = np.array([[30000,13500,26000],[24000,56000,35000],[23000,49000,36000]])

In [9]:
# Matrix_Multiplication
Revenue = np.dot(Price,Units)
Revenue

array([1310000000, 1654000000, 1509000000])

In [11]:
Price_Dollars = np.array([[3,13,26],[24,56,35],[2,4,3]])
Price_Rupee = 75*Price_Dollars
Price_Rupee

array([[ 225,  975, 1950],
       [1800, 4200, 2625],
       [ 150,  300,  225]])